use super::response; use crate::{app::App,pipeline}; use axum::{extract::{Path,State},http::StatusCode,response::Response,Json};use serde_json::{json,Value};use std::sync::Arc;
pub(super) async fn post_feedback(State(app):State<Arc<App>>,Path(id):Path<String>,Json(body):Json<Value>)->Response{let Some(run)=app.db.get_run(&id).ok().flatten()else{return response(StatusCode::NOT_FOUND,json!({"error":"run not found"}))};let action=body["action"].as_str().unwrap_or("");let overall=body["overall"].as_str().unwrap_or("").trim().to_string();let items=Value::Object(body["items"].as_object().cloned().unwrap_or_default());let has=items.as_object().is_some_and(|m|m.values().any(|x|x.as_str().is_some_and(|s|!s.trim().is_empty())));
 match action {
 "accept_concepts" if run.status=="concept_review"=>{if !run.generate_images{if !app.db.cas_status(&id,"concept_review","prompts_ready"){return conflict()}app.db.append_message(&id,"concept_review","event","Prompts are final. Image generation is turned off for this run; copy the prompts to use them elsewhere.");return response(StatusCode::OK,json!({"ok":true,"status":"prompts_ready"}))}
 if !app.db.cas_status(&id,"concept_review","running_images"){return conflict()}pipeline::spawn_images(app.db.clone(),app.providers.clone(),id,app.db_path.clone());response(StatusCode::OK,json!({"ok":true,"status":"running_images"}))}
 "stop_at_prompts" if run.status=="concept_review"=>{if !app.db.cas_status(&id,"concept_review","prompts_ready"){return conflict()}app.db.append_message(&id,"concept_review","event","Stopped at prompts. Copy them to use them elsewhere.");response(StatusCode::OK,json!({"ok":true,"status":"prompts_ready"}))}
 "revise_concepts" if run.status=="concept_review"=>{let no_feedback=body["no_feedback"].as_bool().unwrap_or(false);if overall.is_empty()&&!has&&!no_feedback{return response(StatusCode::BAD_REQUEST,json!({"error":"provide feedback or choose no feedback"}))}
if !app.db.cas_status(&id,"concept_review","running_refine"){return conflict()}app.db.save_feedback(&id,"concepts",&overall,&items);pipeline::spawn_concept_refine(app.db.clone(),app.providers.clone(),id,app.db_path.clone());response(StatusCode::OK,json!({"ok":true,"status":"running_refine"}))}
 "accept_images" if run.status=="image_review"=>{if app.db.cas_status(&id,"image_review","accepted"){app.db.append_message(&id,"image_review","event","Final thumbnail images accepted.");response(StatusCode::OK,json!({"ok":true,"status":"accepted"}))}else{conflict()}}
 "revise_images" if run.status=="image_review"=>{if overall.is_empty()&&!has{return response(StatusCode::BAD_REQUEST,json!({"error":"give feedback for at least one thumbnail"}))}
if !app.db.cas_status(&id,"image_review","running_images"){return conflict()}app.db.save_feedback(&id,"images",&overall,&items);pipeline::spawn_image_refine(app.db.clone(),app.providers.clone(),id,app.db_path.clone());response(StatusCode::OK,json!({"ok":true,"status":"running_images"}))}
 _=>conflict() }
}
fn conflict()->Response{response(StatusCode::CONFLICT,json!({"error":"action is not available in the current review state"}))}
