use crate::{db::{Db,Run}, prompts::*, provider::{extract_json,Providers}, template::render};
use serde_json::{json,Value}; use std::{path::{Path,PathBuf},sync::Arc};
fn wd(db_path:&str,id:&str)->PathBuf{Path::new(db_path).parent().unwrap_or(Path::new("data")).join("runs").join(id)}
fn input(r:&Run)->Value{json!({"topic":r.topic,"summary":r.summary,"channel_url":r.channel_url,"assets":r.assets,"concept_count":r.concept_count})}
fn log(db:&Db,id:&str,phase:&str,sys:&str,user:&str){db.append_message(id,phase,"prompt",&format!("[system prompt]\n{sys}\n\n[user prompt]\n{user}"))}
fn fail(db:&Db,id:&str,phase:&str,e:String){db.fail_run(id,&e);db.append_message(id,phase,"event",&format!("Run failed: {e}"))}
pub fn spawn_run(db:Db,p:Arc<Providers>,id:String,path:String){std::thread::spawn(move||run(db,p,id,path));}
fn run(db:Db,p:Arc<Providers>,id:String,path:String){let work=wd(&path,&id);if !db.cas_status(&id,"queued","running_concepts"){return}let Some(r)=db.get_run(&id).ok().flatten()else{return};let concepts=match concepts(&db,&p,&r,&work){Ok(x)=>x,Err(e)=>return fail(&db,&id,"concepts",e)};db.set_result(&id,&concepts);db.set_status(&id,"running_critique");match critique(&db,&p,&r,concepts,&work){Ok(x)=>{db.set_result(&id,&x);db.cas_status(&id,"running_critique","concept_review");db.append_message(&id,"concept_review","event","Concept prompts are ready for your review.")},Err(e)=>fail(&db,&id,"critique",e)}}
fn concepts(db:&Db,p:&Providers,r:&Run,work:&Path)->Result<String,String>{let u=render(USER_RESEARCH,&input(r))?;log(db,&r.id,"concepts",SYSTEM_RESEARCH,&u);let o=p.run(SYSTEM_RESEARCH,&u,&r.model_research,work).map_err(|e|format!("concept model failed: {e}"))?;db.append_message(&r.id,"concepts","assistant",&o);pretty(parse_concepts(&o,r.concept_count)?)}
fn critique(db:&Db,p:&Providers,r:&Run,mut c:String,work:&Path)->Result<String,String>{for round in 1..=2{let u=render(USER_CRITIQUE,&json!({"input":input(r),"concepts":c}))?;log(db,&r.id,"critique",SYSTEM_CRITIQUE,&u);let o=p.run(SYSTEM_CRITIQUE,&u,&r.model_critique,work).map_err(|e|format!("critique model failed: {e}"))?;db.append_message(&r.id,"critique","assistant",&o);let v=verdict(&o)?;if v["verdict"]=="pass"{db.append_message(&r.id,"critique","event",&format!("Critique passed on round {round}."));return Ok(c)}db.set_status(&r.id,"running_refine");c=refine(db,p,r,&c,&issues(&v),work,"refine")?;db.set_result(&r.id,&c);db.set_status(&r.id,"running_critique");}Ok(c)}
fn refine(db:&Db,p:&Providers,r:&Run,c:&str,f:&str,work:&Path,phase:&str)->Result<String,String>{let u=render(USER_FIX,&json!({"input":input(r),"concepts":c,"feedback":f}))?;log(db,&r.id,phase,SYSTEM_FIX,&u);let o=p.run(SYSTEM_FIX,&u,&r.model_fix,work).map_err(|e|format!("refiner failed: {e}"))?;db.append_message(&r.id,phase,"assistant",&o);pretty(parse_concepts(&o,r.concept_count)?)}
pub fn spawn_concept_refine(db:Db,p:Arc<Providers>,id:String,path:String){std::thread::spawn(move||{let work=wd(&path,&id);let out=(||{let r=db.get_run(&id)?.ok_or("run not found")?;let f=db.latest_feedback(&id).ok_or("feedback missing")?;refine(&db,&p,&r,r.result.as_deref().ok_or("concepts missing")?,&feedback(&f.overall,&f.items,true),&work,"human_refine")})();match out{Ok(c)=>{db.set_result(&id,&c);let _=db.cas_status(&id,"running_refine","concept_review");},Err(e)=>fail(&db,&id,"human_refine",e)}});}
pub fn spawn_images(db:Db,p:Arc<Providers>,id:String,path:String){std::thread::spawn(move||{let work=wd(&path,&id);let out=(||{let r=db.get_run(&id)?.ok_or("run not found")?;let c=r.result.as_deref().ok_or("concepts missing")?;image_call(&db,&p,&r,c,None,&work,"images")})();match out{Ok(x)=>{db.set_result(&id,&x);db.cas_status(&id,"running_images","image_review");db.append_message(&id,"image_review","event","Generated thumbnails are ready for approval.")},Err(e)=>fail(&db,&id,"images",e)}});}
pub fn spawn_image_refine(db:Db,p:Arc<Providers>,id:String,path:String){std::thread::spawn(move||{let work=wd(&path,&id);let out=(||{let r=db.get_run(&id)?.ok_or("run not found")?;let f=db.latest_feedback(&id).ok_or("feedback missing")?;image_call(&db,&p,&r,r.result.as_deref().ok_or("images missing")?,Some(&feedback(&f.overall,&f.items,false)),&work,"image_refine")})();match out{Ok(x)=>{db.set_result(&id,&x);let _=db.cas_status(&id,"running_images","image_review");},Err(e)=>fail(&db,&id,"image_refine",e)}});}
fn image_call(db:&Db,p:&Providers,r:&Run,current:&str,feedback:Option<&str>,work:&Path,phase:&str)->Result<String,String>{let u=render(USER_IMAGE,&json!({"input":input(r),"current":current,"feedback":feedback}))?;log(db,&r.id,phase,SYSTEM_IMAGE,&u);let o=p.run(SYSTEM_IMAGE,&u,&r.model_image,work).map_err(|e|format!("image model failed: {e}"))?;db.append_message(&r.id,phase,"assistant",&o);pretty(parse_images(&o,current)?)}
fn feedback(overall:&str,items:&Value,allow_empty:bool)->String{let mut a=Vec::new();if !overall.trim().is_empty(){a.push(format!("Overall: {}",overall.trim()))}
if let Some(m)=items.as_object(){for(id,x)in m{if let Some(s)=x.as_str().filter(|s|!s.trim().is_empty()){a.push(format!("{id}: {}",s.trim()))}}}
if a.is_empty()&&allow_empty{"No user feedback was supplied. Independently improve clarity, curiosity, channel fit, and mobile readability.".into()}else{a.join("\n")}}
fn pretty(v:Value)->Result<String,String>{serde_json::to_string_pretty(&v).map_err(|e|e.to_string())}
fn parse_concepts(text:&str,n:u8)->Result<Value,String>{let raw=extract_json(text).ok_or("no JSON in concept output")?;let mut v:Value=serde_json::from_str(&raw).map_err(|e|e.to_string())?;let a=v.get_mut("concepts").and_then(Value::as_array_mut).ok_or("output must include concepts array")?;if a.len()!=n as usize{return Err(format!("expected {n} concepts, got {}",a.len()))}for(i,x)in a.iter_mut().enumerate(){let o=x.as_object_mut().ok_or("concept must be object")?;o.insert("id".into(),json!(format!("c{}",i+1)));if o.get("prompt").and_then(Value::as_str).is_none(){return Err("each concept needs prompt".into())}}Ok(v)}
fn parse_images(text:&str,current:&str)->Result<Value,String>{let raw=extract_json(text).ok_or("no JSON in image output")?;let mut v:Value=serde_json::from_str(&raw).map_err(|e|e.to_string())?;let a=v.get_mut("thumbnails").and_then(Value::as_array_mut).ok_or("output must include thumbnails array")?;if a.is_empty(){return Err("no thumbnails returned".into())}
if let Ok(old)=serde_json::from_str::<Value>(current){if let Some(old)=old.get("thumbnails").and_then(Value::as_array){for x in old{if let Some(id)=x.get("id"){if !a.iter().any(|y|y.get("id")==Some(id)){a.push(x.clone())}}}}}Ok(v)}
fn verdict(text:&str)->Result<Value,String>{let raw=extract_json(text).ok_or("no JSON verdict")?;let v:Value=serde_json::from_str(&raw).map_err(|e|e.to_string())?;if ["pass","revise"].contains(&v["verdict"].as_str().unwrap_or("")){Ok(v)}else{Err("verdict must be pass or revise".into())}}
fn issues(v:&Value)->String{v["issues"].as_array().map(|a|a.iter().filter_map(Value::as_str).collect::<Vec<_>>().join("\n")).filter(|s|!s.is_empty()).unwrap_or_else(||"Improve clarity and click appeal.".into())}
